language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install coveralls
  - pip install -r requirements-dev.txt

script:
  - nosetests -v --with-coverage --cover-package=tilda/
  - flake8 tilda

after_success:
  coveralls
